<template>
  <div class="loading">
    <div class="loading--inner">
      <div></div>
    </div>
  </div>
</template>
<style type="text/css">
  @keyframes loading--inner {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }

    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }

  .loading--inner div {
    position: absolute;
    width: 92px;
    height: 92px;
    border: 8px solid #fb641c;
    border-top-color: transparent;
    border-radius: 50%;
  }

  .loading--inner div {
    animation: loading--inner 1.6949152542372883s linear infinite;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }

  .loading {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: #f1f2f3;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100vh;
    opacity: 0.5;
  }

  .loading--inner {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0;
    /* see note above */
  }

  .loading--inner div {
    box-sizing: content-box;
  }

  /* generated by https://loading.io/ */
</style>
